apiVersion: v1
kind: Pod
metadata:
  name:   test-cm
spec:
  containers:
    - name:    busybox
      image:   busybox
      args: [sh, -c, 'while true; do echo "hello there!"; sleep 10; done']
      volumeMounts:
        - name: test
          mountPath: /test
        - name: test2
          mountPath: /test-extras
  volumes:
    - name: test
      configMap:
        name: test-cm
    - name: test2
      configMap:
        name: test-cm2
        optional: true

