apiVersion: v1
kind: Pod
metadata:
  name:   pause
spec:
  containers:
    - name:    pause
      image: gcr.io/google_containers/pause
      volumeMounts:
      - mountPath: /usr/share/k8s
        name: k8s-volume
  volumes:
  - name: k8s-volume
    gitRepo:
      repository: "https://github.com/kubernetes/kubernetes.git"
